POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Toyota",
  "model": "Camry",
  "year": 2012,
  "mileage": 10000,
  "price": 10000,
  "lng": 0,
  "lat": 0,
  "price": 10000
}

### Approve a report
PATCH http://localhost:3000/reports/7
content-type: application/json

{
  "approved": false
}