### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "poop3ww22@freffddy.com",
  "password": "fuckers"
}

### SignIn
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "poop2@freddy.com",
  "password": "fuckers"
}

### Get Me
GET http://localhost:3000/auth/whoami

### LogOut
POST http://localhost:3000/auth/signout

### Find user by ID
GET http://localhost:3000/auth/5

### Find all users by email
GET http://localhost:3000/auth?email=balls@fred.com

### Delete a user
DELETE http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/6
content-type: application/json

{
  "email": "freddickstone@balls.com"
  }


